[package]
name = "fuse"
version = "0.2.6"
authors = ["Andreas Neuhaus <zargony@zargony.com>"]
build = "build.rs"
description = "Rust library for filesystems in userspace (FUSE)"
homepage = "https://github.com/zargony/rust-fuse"
repository = "https://github.com/zargony/rust-fuse"
readme = "README.md"
keywords = ["fuse", "filesystem", "system", "bindings"]
license = "MIT"

[build-dependencies]
pkg-config = "*"

[dependencies]
log = "*"
time = "*"
libc = "0.1"

[lib]
name = "fuse"
path = "src/lib.rs"
